### ISSUE TITLE
Theorem has a caption

### ISSUE THREAD

**Issue by waynee95** [sahasatvik/typst-theorems#10]
```
#import "@preview/ctheorems:1.0.0": *

#let theorem = thmbox("theorem", "Theorem")
#let definition = thmbox("definition", "Definition", inset: (x: 1.2em, top: 1em))
#let proof = thmplain(
  "proof",
  "Proof",
  base: "theorem",
  bodyfmt: body => [#body #h(1fr) $square$]
).with(numbering: none)

#definition[
Cool definition
]

#theorem("Very cool theorem")[
  hello world
]

#proof[
  a proof
]
```

The above will display the Theorem with a caption. I don't think this is intended?

**Comment by maxtremblay** [comment]
I have a similar problem. I have a caption for theorems with name.

**Comment by sahasatvik** [comment]
Please use `#show: thmrules` after the import, that ought to fix the styling.

**Comment by ivaquero** [comment]
`#show: thmrules` works, could you please make it as the default?

**Comment by sahasatvik** [comment]
Unfortunately, typst doesn't carry over `#show` rules from an import, so this manual intervention is necessary. I'll try and make this more clear in the documentation.

**Comment by maxtremblay** [comment]
Unfortunately, I still have captions with `#show: thmrules`.  Maybe I am doing something wrong.

Here is everything related to this package in my typst file:

```typst
#import "@preview/ctheorems:1.0.0": *
#show: thmrules

#let thmstyle(counter, name, color) = thmbox(
  counter,
  name, 
  inset: (x: 1em, y: 1em), 
  fill: color.lighten(90%), 
  stroke: color,
  base: none,
)


#let theorem = thmstyle("theorem", "Theorem", orange)
#let proposition = thmstyle("theorem", "Proposition", color-nq)
#let definition = thmstyle("definition", "Definition", seaweed)
#let example = thmstyle("example", "Example", pink-qubit)

#let proof = thmplain(
  "proof",
  "Proof",
  base: "theorem",
  inset: (x: 0em, top: 0em),
  bodyfmt: body => [#body #h(1fr) $square$],
).with(numbering:none)

```

**Comment by sahasatvik** [comment]
@maxtremblay I've rendered a short document based on your code [here](https://typst.app/project/rR89r-xPGQdeHHrpaDAqUE) and things seem to be ok. I can think of a couple of reasons why this might be different on your end.

- You are importing other packages which mess with `#show` rules related to `figures`. You might want to put the `#show: thmrules` line after all other imports.
- Your `typst` compiler is not updated? (I really don't think this ought to affect things though)

Perhaps taking a look at the rest of the document would help.

**Comment by maxtremblay** [comment]
Thanks. I move the `$show: thmrules` after all imports and it fixed the issue.

**Comment by maxtremblay** [comment]
Thanks, I don't exactly understand why, but moving some `#show` rules around solved the
