### ISSUE TITLE
Extra space after the name of an unnumbered theorem

### ISSUE THREAD

**Issue by nullst** [sahasatvik/typst-theorems#11]
As shown in the example and documentation, unnumbered theorem environments appear to have extra space after the name:

![Screenshot from 2023-11-04 14-03-47](https://github.com/sahasatvik/typst-theorems/assets/7746216/158d545f-0b3c-4518-bf42-8921aac1557e)

It would look better if rendered as "Example: The numbers...", i.e., with no space before the colon character. This would also be consistent with the LaTeX amsthm behavior.

I don't know typst, but it seems to me that the issue appears due to the incompatibility between the lines https://github.com/sahasatvik/typst-theorems/blob/1f56a2002eae445a6de8c6883687afb43cb62d3c/theorems.typ#L34 (setting number to empty text) and https://github.com/sahasatvik/typst-theorems/blob/1f56a2002eae445a6de8c6883687afb43cb62d3c/theorems.typ#L123 (where `[]` is not `none`).

**Comment by sahasatvik** [comment]
I think that's exactly right, will fix!
