### ISSUE TITLE
Include content other than names in parentheses

### ISSUE THREAD

**Issue by lukasjuhrich** [sahasatvik/typst-theorems#13]
I will want to write something like the following:

> **Theorem** (Term rewriting system; [BN98, Def. 4.2.1])

or  just

> **Theorem** ([BN98, Def. 4.2.1])

The problem is that there is only the identifier and it only accepts a `string`, while I would need to be able to supply `content`. Viz, the following does not work:

```typst
#let thm = thmbox("theorem", "Theorem", fill: rgb("#eeffee"), breakable: true)
#thm([Term rewriting system, @baader_nipkow[Def.~4.2.1]])[…]
```

Do you have any ideas on how to implement this or what a workaround might be?

**Comment by sahasatvik** [comment]
Something like the following seems to work:
```typst
#import "@preview/ctheorems:1.1.0": *
#show: thmrules

#set heading(numbering: "1.1")

#let thm = thmbox("theorem", "Theorem", fill: rgb("#eeffee"), breakable: true)

= Theorems
#thm([First])[ ... ] <first>
#thm([Extension of @first in $CC$])[ ... ]
```
The theorem `name` ought to handle content just fine; could you share a more complete example of your issue?

**Comment by lukasjuhrich** [comment]
I cannot reproduce my own example, so closing for now. Perhaps I did something different, I will reopen with a minimally reproducing example if it comes up again.
