### ISSUE TITLE
How can I make a breakable theorem?

### ISSUE THREAD

**Issue by ice1000** [sahasatvik/typst-theorems#21]
![image](https://github.com/sahasatvik/typst-theorems/assets/16398479/2ac64488-902b-4f7d-94a0-f5088ea2472f)

There are times I have a semi-page long theorem, and I wish it can be broken down into pages. Is this feasible?

**Comment by ice1000** [comment]
![image](https://github.com/sahasatvik/typst-theorems/assets/16398479/a64fa382-bfb8-4bf8-9afa-89f9ab906a80)

Looks like this is all we need

**Comment by sahasatvik** [comment]
Simply supply `breakable: true`.

```typst
#import "@preview/ctheorems:1.1.2": *
#show: thmrules

#set page(width: 6in, height: 2in)

#let theorem = thmbox(
  "theorem",
  "Theorem",
  breakable: true,
  fill: rgb("#eeeeee")
)

#theorem[
  #lorem(100)
]
```
![Screenshot from 2024-04-02 18-45-05](https://github.com/sahasatvik/typst-theorems/assets/16478483/8833e4ae-2602-40ba-b7be-8287bf121012)

You can even override this individually, like `#theorem(breakable: false)[ ...content... ]`.

This seems like a common enough issue that I'll probably remove the default `breakable: false` in v2.0.0.

**Comment by sahasatvik** [comment]
Also see https://github.com/sahasatvik/typst-theorems/issues/5#issuecomment-1962483288.

**Comment by ice1000** [comment]
Thank you!
