### ISSUE TITLE
Allow a theorem to (optionally) be broken over several pages

### ISSUE THREAD

**Issue by jsimonrichard** [sahasatvik/typst-theorems#24]
Hello, I'm quite new to ctheorems and typst in general so I appreciate your patience if I'm missing something obvious.

I would like to spread a medium length definition over two pages. It's small enough to fit on one page, but the surrounding text forces it to jump to the next page, leaving a rather large area of white space. Here's a screenshot.

![image](https://github.com/sahasatvik/typst-theorems/assets/15972974/57db0461-338f-4497-978b-b77410ea31e5)

I know whether or not this should be all on one page is probably a matter of opinion, but it would be nice to have to option to split this over two pages.

Is there currently a way to achieve this?

**Comment by sahasatvik** [comment]
Please take a look at https://github.com/sahasatvik/typst-theorems/issues/21#issuecomment-2032022610. You can set `breakable: true` either when defining your environment, or on an individual basis.

**Comment by jsimonrichard** [comment]
Ah, thank you. I missed that in the manual, but I see it now.
