### ISSUE TITLE
Theorem Environments across multiple pages

### ISSUE THREAD

**Issue by balltar** [sahasatvik/typst-theorems#38]
Does the package currently support having theorems span across a page? 
Currently whenever this happens it just moves the entire theorem box to the next page leaving a huge blank space on the current page.

**Comment by FlandiaYingman** [comment]
Add `breakable: true` to thmbox. thmplain is already breakable.

![image](https://github.com/user-attachments/assets/cc683979-c903-4b8b-9930-4cddc7484f28)

**Comment by PgBiel** [comment]
If you're using Typst 0.12, you may be affected by a recent change to figure show rules, so you may have to use my PR's branch in the meantime: https://github.com/sahasatvik/typst-theorems/pull/39

**Comment by balltar** [comment]
I'm using the online app. Setting `breakable: true` didn't resolve the issue. I assume this is because of @PgBiel comment?
Is there a way to use "PR's branch" through the web app version?

**Comment by PgBiel** [comment]
> Is there a way to use "PR's branch" through the web app version?

Copy the following file to your project, and replace `#import "@preview/ctheorems:version"` with `#import "theorems.typ"` (adjusted to the path where you save the file): https://raw.githubusercontent.com/sahasatvik/typst-theorems/2e506e3ae25e79d4931da79f1a979022ee860e72/theorems.typ

**Comment by balltar** [comment]
@PgBiel that did the trick. Thanks! Hopefully that branch gets merged soon!
