### ISSUE TITLE
Centering Issue

### ISSUE THREAD

**Issue by balltar** [sahasatvik/typst-theorems#41]
I opened up my document today and suddenly all of the text in my thmbox's and thmproof's is centered! It hasn't been like this... I am using the web version and I assume this is because some latest version of Typst made some breaking change? Is there any way around this.

**Comment by jmigual** [comment]
Same here. For now I solved it (partially) adding the `bodyfmt` parameter:

```typst
#let definition = ctheorems.thmbox(
  "definition", 
  "Definition",
  bodyfmt: body => [
    #set align(left)
    #body
  ]
)
```

**Comment by balltar** [comment]
Thanks! That almost works except now the text is below the proposition title and the title is centered. Do you know how to left align the "Proposition 0.2:" below and have the text come immediately after it?

![propositioncentering](https://github.com/user-attachments/assets/094b03c9-97be-4132-80f7-7fc1d29dc325)

**Comment by balltar** [comment]
This is a Typst version issue. See #39 for the merge request to resolve this. See #38 for a temporary fix.

**Comment by jmigual** [comment]
Thanks!
