### ISSUE TITLE
Everything is centered

### ISSUE THREAD

**Issue by czhang2718** [sahasatvik/typst-theorems#42]
Thmbox is centered by default. [The example](https://typst.app/universe/package/ctheorems) compiles differently now.

**Comment by joshuagawley** [comment]
This is from a variant of thmbox in my own project; maybe the default alignment of `block` was changed in Typst 0.12.0 to be centered.

I fixed it in my project by just wrapping the block content in an `align(left, ...)` block

Before: <img width="1150" alt="image" src="https://github.com/user-attachments/assets/404b3072-e040-45dc-98e2-2027d1a1d487">

After: <img width="1229" alt="image" src="https://github.com/user-attachments/assets/b88686c4-e2d8-4346-a782-ee8079fc84b8">

**Comment by balltar** [comment]
This issue has been noted in #40, #41, and will eventually be resolved through a version bump (#43) from the merge #39.

A temporary fix is mentioned in #38.

**Comment by sahasatvik** [comment]
The version has been bumped to v1.1.3 today, and is available [officially](https://typst.app/universe/package/ctheorems).

**Comment by 3f6a** [comment]
I'm seeing this issue now, latest version of Typst and this package at the time of writing.

Is this issue really fixed?
