### ISSUE TITLE
Boxes are not breakable (typst 0.12 + ctheorems 1.1.3)

### ISSUE THREAD

**Issue by cgahr** [sahasatvik/typst-theorems#44]
I'm using typst 0.12, and boxes don't break between pages, even if they are set to breakable. 

See the follow MWE to reproduce:
```
#import "@preview/ctheorems:1.1.3": *

#let example(title, body) = box(
  width: 100%,
  thmbox(
    "example",
    "Example",
    breakable: true,
    fill: rgb("#eeffee"),
  ).with(numbering: none)(title, body),
)

#example([test])[#lorem(1000)]
```

**Comment by YDX-2147483647** [comment]
I just confirmed that the following works. Could you explain your purpose of wrapping `box(width: 100%, …)`?

```typst
#import "@preview/ctheorems:1.1.3": thmbox, thmrules
#show: thmrules

#let example = thmbox(
    "example",
    "Example",
    breakable: true,
    fill: rgb("#eeffee"),
).with(numbering: none)

#example[test][#lorem(1000)]
```

![](https://github.com/user-attachments/assets/b7f4c741-07ba-4761-9047-30e09fb6eb6d)


[Box Function – Typst Documentation](https://typst.app/docs/reference/layout/box/#summary):
> Box: An **inline-level** container that sizes content.
>
> All elements except inline math, text, and boxes are block-level and cannot occur inside of a paragraph. The box function can be used to integrate such elements into a paragraph.

**Comment by cgahr** [comment]
Hmm, no not really. I don't know why I did this in the first place..

Thanks a lot!

**Comment by YDX-2147483647** [comment]
You are welcome! So I guess this is the problem you described in https://github.com/sahasatvik/typst-theorems/pull/39?

**Comment by cgahr** [comment]
Yes, exactly. I thought I had the same issue, but then realized that this fix was already merged.
