### ISSUE TITLE
Centered text in theorems

### ISSUE THREAD

**Issue by davidwholm** [sahasatvik/typst-theorems#45]
Hey! I want to say thank you for creating this package, first and foremost!

Now, I am aware of the previous issues related to centering #41 #42 #40, as well as the version bump #39 that was supposed to fix it. I still have centered definition/theorem boxes though; I am using the exact configuration shown on the universe page:

```typ
#import "@preview/ctheorems:1.1.3": *
#show: thmrules.with(qed-symbol: $square$)

#set page(width: 16cm, height: auto, margin: 1.5cm)
#set heading(numbering: "1.1.")

#let theorem = thmbox("theorem", "Theorem", fill: rgb("#eeffee"))
#let corollary = thmplain(
  "corollary",
  "Corollary",
  base: "theorem",
  titlefmt: strong
)
#let definition = thmbox("definition", "Definition", inset: (x: 1.2em, top: 1em))

#let example = thmplain("example", "Example").with(numbering: none)
#let proof = thmproof("proof", "Proof")
```

An example of how it looks:
<img width="746" alt="image" src="https://github.com/user-attachments/assets/e8a15043-ece3-47dd-96a9-876e7b0b60c3" />

I'm using the latest Typst version 0.12.

Any ideas on what could cause this?

**Comment by sahasatvik** [comment]
I have created a demo with the same preamble [here](https://typst.app/project/r0IYxCUgdxCgUHPbTq0qcG), and can't reproduce your issue. It is possible that some other definitions/packages in your document are overriding some of the `show` rules which `ctheorems` uses; can you share a minimal working example?

**Comment by davidwholm** [comment]
Thank you for your answer! I realized that I had the preamble in a "lib.typ" file which I then imported, and now that I put it in the main file like you did it works! I am not that proficient with Typst yet, I take it it's something with the show and set rules not working properly when just imported into another file... My bad :) Thanks!

**Comment by barddust** [comment]
I've met this problem.

Windows11, Typst 0.12.

It happens when importing `thmbox` defined in another file.

Say `mathconf.typ`:

``` typst
#import "@preview/ctheorems:1.1.3": *
#show: thmrules.with(qed-symbol: $square$)
#let theorem = thmbox("theorem", "Theorem", fill: rgb("#eeffee"))
```

`a.typ`:

``` typst
#import "mathconf.typ": theorem

= TestA

#theorem[
  let $A >= B$
]
```

and `b.typ`:

``` typst
#import "@preview/ctheorems:1.1.3": *
#show: thmrules.with(qed-symbol: $square$)
#let theorem = thmbox("theorem", "Theorem", fill: rgb("#eeffee"))

= TestB

#theorem[
  let $A >= B$
]
```

Compile `a.typ` and `b.typ`:

![image](https://github.com/user-attachments/assets/e3b8b0ce-36c4-4825-b3e0-df98cf4b91b2)

![image](https://github.com/user-attachments/assets/ebe55a00-b6d0-481e-9ba2-680ceeac7737)

**Comment by sahasatvik** [comment]
This is because `#show` rules in Typst do not get carried over imports; as far as I am aware, there is no way to change this behavior. The cleanest way of making `a.typ` work is moving the `#show: thmrules` line into it.

**Comment by 3f6a** [comment]
I am seeing this problem now. Why was this issue closed?

**Comment by sahasatvik** [comment]
Can you please share a minimal working example of your issue?
