### ISSUE TITLE
Theorem doesn't work on several pages

### ISSUE THREAD

**Issue by HarmoGlace** [sahasatvik/typst-theorems#5]
For very long theorems, once its content exceeds the page limit, it does the following thing:
![image](https://github.com/sahasatvik/typst-theorems/assets/23212967/766b2184-df83-498f-a5b8-672e1aadc4c3)

It is reproducible with the following code:
```typst
#theorem(name: "test")[
  #lorem(1000)
]
````

**Comment by sahasatvik** [comment]
This is related to the `block` wrapper; setting `breakable: true` fixes this.
```typst
#import "@preview/ctheorems:1.1.1": *
#show: thmrules

#let theorem = thmbox("theorem", "Theorem", fill: rgb("#eeffee"), breakable: true)

#theorem("test")[
  #lorem(1000)
]
```
