### ISSUE TITLE
Add to the Typst package repos

### ISSUE THREAD

**Issue by ParadaCarleton** [sahasatvik/typst-theorems#6]
See [here](https://github.com/typst/packages/tree/main).

**Comment by sahasatvik** [comment]
I have been away from this project for quite a while, and seem to have missed a lot of new features!

I believe that [lemmify](https://github.com/typst/packages/tree/main/packages/preview/lemmify/0.1.2) is much more up to date. [ctheorems](https://github.com/typst/packages/tree/main/packages/preview/ctheorems/0.1.0) looks like an attempt to build on this system if that's what you're looking for.

**Comment by sahasatvik** [comment]
Update: This package is now aligned with [ctheorems](https://github.com/typst/packages/tree/main/packages/preview/ctheorems/1.0.0). Further updates will eventually appear there.
